In [1]:
import pybliometrics
from pybliometrics.scopus import ScopusSearch
from pybliometrics.scopus.utils import config
from pybliometrics.scopus import AuthorRetrieval
import sys
import pandas as pd
import time

s = ScopusSearch("AU-ID(56344636600)")
my_papers = s.results
my_papers = [[x.title, x.eid, x.doi] for x in my_papers if x.eid not in ["2-s2.0-84906819575", "2-s2.0-84976641685"]]
my_papers

[['HAMLET: A framework for Human-centered AutoML via Structured Argumentation',
  '2-s2.0-85145965157',
  '10.1016/j.future.2022.12.035'],
 ['Trajectory-Based Spatiotemporal Entity Linking',
  '2-s2.0-85096846619',
  '10.1109/TKDE.2020.3036633'],
 ['Multi-sensor profiling for precision soil-moisture monitoring',
  '2-s2.0-85129541562',
  '10.1016/j.compag.2022.106924'],
 ['Enhancing Cubes with Models to Describe Multidimensional Data',
  '2-s2.0-85107683405',
  '10.1007/s10796-021-10147-3'],
 ['COOL: A framework for conversational OLAP',
  '2-s2.0-85103428030',
  '10.1016/j.is.2021.101752'],
 ['Cost-based Optimization of Multistore Query Plans',
  '2-s2.0-85139405955',
  '10.1007/s10796-022-10320-2'],
 ['Insight-Based Vocalization of\xa0OLAP Sessions',
  '2-s2.0-85137993971',
  '10.1007/978-3-031-15740-0_15'],
 ['Describing Multidimensional Data Through Highlights (Discussion Paper)',
  '2-s2.0-85137469232',
  None],
 ['A Survey and Experimental Study on Privacy-Preserving Trajectory Data Publishing',
  '2-s2.0-85132525373',
  '10.1109/TKDE.2022.3174204'],
 ['Suggesting assess queries for interactive analysis of multidimensional data',
  '2-s2.0-85129353199',
  '10.1109/TKDE.2022.3171516'],
 ['Making data platforms smarter with MOSES',
  '2-s2.0-85109035166',
  '10.1016/j.future.2021.06.031'],
 ['Conversational OLAP', '2-s2.0-85118769792', None],
 ['Optimizing Execution Plans in a Multistore',
  '2-s2.0-85115134032',
  '10.1007/978-3-030-82472-3_11'],
 ['Conversational OLAP in action',
  '2-s2.0-85113716450',
  '10.5441/002/edbt.2021.74'],
 ['Assess queries for interactive analysis of data cubes',
  '2-s2.0-85113712544',
  '10.5441/002/edbt.2021.12'],
 ['Crop Management with the IoT: An Interdisciplinary Survey',
  '2-s2.0-85100942957',
  '10.3390/agronomy11010181'],
 ['DART: De-Anonymization of personal gazetteers through social trajectories',
  '2-s2.0-85093926143',
  '10.1016/j.jisa.2020.102634'],
 ['A-BI<sup>+</sup>: A framework for Augmented Business Intelligence',
  '2-s2.0-85082441558',
  '10.1016/j.is.2020.101520'],
 ['Summarization and visualization of multi-level and multi-dimensional itemsets',
  '2-s2.0-85079239065',
  '10.1016/j.ins.2020.02.006'],
 ['Towards a Conceptual Model for Data Narratives',
  '2-s2.0-85097380415',
  '10.1007/978-3-030-62522-1_19'],
 ['Supporting the generation of data narratives', '2-s2.0-85095734112', None],
 ['OLAP Querying of Document Stores in the Presence of Schema Variety',
  '2-s2.0-85090883258',
  None],
 ['The Tell-Tale Cube', '2-s2.0-85090100247', '10.1007/978-3-030-54832-2_16'],
 ['Towards conversational OLAP', '2-s2.0-85082444588', None],
 ['Social BI to understand the debate on vaccines on the Web and social media: unraveling the anti-, free, and pro-vax communities in Italy',
  '2-s2.0-85070525370',
  '10.1007/s13278-019-0590-x'],
 ['Map-matching on big data: A distributed and efficient algorithm with a hidden Markov model',
  '2-s2.0-85070329171',
  '10.23919/MIPRO.2019.8757119'],
 ['Augmented business intelligence', '2-s2.0-85062645475', None],
 ['A Similarity Function for Multi-Level and Multi-Dimensional Itemsets',
  '2-s2.0-85051863772',
  None],
 ['Towards a foundational API for resilient distributed systems design',
  '2-s2.0-85035209468',
  '10.1109/FAS-W.2017.116']]

In [2]:
dfp = pd.DataFrame(my_papers, columns=["Paper title", "Paper eid", "Paper doi"])
dfp.sort_values(["Paper title"], ignore_index=True)

,Paper title,Paper eid,Paper doi
0,A Similarity Function for Multi-Level and Mult...,2-s2.0-85051863772,None
1,A Survey and Experimental Study on Privacy-Pre...,2-s2.0-85132525373,10.1109/TKDE.2022.3174204
2,A-BI<sup>+</sup>: A framework for Augmented Bu...,2-s2.0-85082441558,10.1016/j.is.2020.101520
3,Assess queries for interactive analysis of dat...,2-s2.0-85113712544,10.5441/002/edbt.2021.12
4,Augmented business intelligence,2-s2.0-85062645475,None
5,COOL: A framework for conversational OLAP,2-s2.0-85103428030,10.1016/j.is.2021.101752
6,Conversational OLAP,2-s2.0-85118769792,None
7,Conversational OLAP in action,2-s2.0-85113716450,10.5441/002/edbt.2021.74
8,Cost-based Optimization of Multistore Query Plans,2-s2.0-85139405955,10.1007/s10796-022-10320-2
9,Crop Management with the IoT: An Interdiscipli...,2-s2.0-85100942957,10.3390/agronomy11010181
10,DART: De-Anonymization of personal gazetteers ...,2-s2.0-85093926143,10.1016/j.jisa.2020.102634
11,Describing Multidimensional Data Through Highl...,2-s2.0-85137469232,None
12,Enhancing Cubes with Models to Describe Multid...,2-s2.0-85107683405,10.1007/s10796-021-10147-3
13,HAMLET: A framework for Human-centered AutoML ...,2-s2.0-85145965157,10.1016/j.future.2022.12.035
14,Insight-Based Vocalization of OLAP Sessions,2-s2.0-85137993971,10.1007/978-3-031-15740-0_15
15,Making data platforms smarter with MOSES,2-s2.0-85109035166,10.1016/j.future.2021.06.031
16,Map-matching on big data: A distributed and ef...,2-s2.0-85070329171,10.23919/MIPRO.2019.8757119
17,Multi-sensor profiling for precision soil-mois...,2-s2.0-85129541562,10.1016/j.compag.2022.106924
18,OLAP Querying of Document Stores in the Presen...,2-s2.0-85090883258,None
19,Optimizing Execution Plans in a Multistore,2-s2.0-85115134032,10.1007/978-3-030-82472-3_11
20,Social BI to understand the debate on vaccines...,2-s2.0-85070525370,10.1007/s13278-019-0590-x
21,Suggesting assess queries for interactive anal...,2-s2.0-85129353199,10.1109/TKDE.2022.3171516
22,Summarization and visualization of multi-level...,2-s2.0-85079239065,10.1016/j.ins.2020.02.006
23,Supporting the generation of data narratives,2-s2.0-85095734112,None
24,The Tell-Tale Cube,2-s2.0-85090100247,10.1007/978-3-030-54832-2_16
25,Towards a Conceptual Model for Data Narratives,2-s2.0-85097380415,10.1007/978-3-030-62522-1_19
26,Towards a foundational API for resilient distr...,2-s2.0-85035209468,10.1109/FAS-W.2017.116
27,Towards conversational OLAP,2-s2.0-85082444588,None
28,Trajectory-Based Spatiotemporal Entity Linking,2-s2.0-85096846619,10.1109/TKDE.2020.3036633

In [3]:
acc = []
for paper in my_papers:
    q = f"REF({paper[1]})"
    s = ScopusSearch(q, refresh=0)
    print(s)
    res = s.results
    if res is not None and len(res) > 0:
        for x in res:
            acc = acc + [paper + [x.title, x.eid, x.doi]]
    else:
        acc = acc + [paper + ["", "", ""]]

Search 'REF(2-s2.0-85145965157)' yielded 0 documents as of 2023-12-18
Search 'REF(2-s2.0-85096846619)' yielded 10 documents as of 2023-12-18:
    2-s2.0-85174707802
    2-s2.0-85149039992
    2-s2.0-85132525373
    2-s2.0-85123164859
    2-s2.0-85096846619
    2-s2.0-85132711904
    2-s2.0-85137576224
    2-s2.0-85137872696
    2-s2.0-85136425113
    2-s2.0-85121922321
Search 'REF(2-s2.0-85129541562)' yielded 6 documents as of 2023-12-18:
    2-s2.0-85176949684
    2-s2.0-85166665907
    2-s2.0-85166187482
    2-s2.0-85153035011
    2-s2.0-85153930157
    2-s2.0-85173428371
Search 'REF(2-s2.0-85107683405)' yielded 9 documents as of 2023-12-18:
    2-s2.0-85129353199
    2-s2.0-85160881368
    2-s2.0-85165002810
    2-s2.0-85173478290
    2-s2.0-85153354053
    2-s2.0-85153334849
    2-s2.0-85125529748
    2-s2.0-85137993971
    2-s2.0-85137469232
Search 'REF(2-s2.0-85103428030)' yielded 9 documents as of 2023-12-18:
    2-s2.0-85129353199
    2-s2.0-85145965157
    2-s2.0-85171481610
    2-s2.0-85166634616
    2-s2.0-85165494524
    2-s2.0-85153334849
    2-s2.0-85137993971
    2-s2.0-85137469232
    2-s2.0-85118769792
Search 'REF(2-s2.0-85139405955)' yielded 0 documents as of 2023-12-18
Search 'REF(2-s2.0-85137993971)' yielded 0 documents as of 2023-12-18
Search 'REF(2-s2.0-85137469232)' yielded 0 documents as of 2023-12-18
Search 'REF(2-s2.0-85132525373)' yielded 10 documents as of 2023-12-18:
    2-s2.0-85174707802
    2-s2.0-85145256040
    2-s2.0-85151097067
    2-s2.0-85174704562
    2-s2.0-85144019298
    2-s2.0-85138804472
    2-s2.0-85136425113
    2-s2.0-85136226665
    2-s2.0-85110326989
    2-s2.0-85121922321
Search 'REF(2-s2.0-85129353199)' yielded 1 document as of 2023-12-18:
    2-s2.0-85153334849
Search 'REF(2-s2.0-85109035166)' yielded 10 documents as of 2023-12-18:
    2-s2.0-85139405955
    2-s2.0-85160651880
    2-s2.0-85145965157
    2-s2.0-85145253028
    2-s2.0-85173485992
    2-s2.0-85162176776
    2-s2.0-85158965423
    2-s2.0-85142431269
    2-s2.0-85130740902
    2-s2.0-85125785920
Search 'REF(2-s2.0-85118769792)' yielded 0 documents as of 2023-12-18
Search 'REF(2-s2.0-85115134032)' yielded 5 documents as of 2023-12-18:
    2-s2.0-85139405955
    2-s2.0-85145965157
    2-s2.0-85173485992
    2-s2.0-85160752944
    2-s2.0-85130740902
Search 'REF(2-s2.0-85113716450)' yielded 1 document as of 2023-12-18:
    2-s2.0-85118769792
Search 'REF(2-s2.0-85113712544)' yielded 7 documents as of 2023-12-18:
    2-s2.0-85129353199
    2-s2.0-85165002810
    2-s2.0-85173478290
    2-s2.0-85153334849
    2-s2.0-85107683405
    2-s2.0-85137993971
    2-s2.0-85137469232
Search 'REF(2-s2.0-85100942957)' yielded 26 documents as of 2023-12-18:
    2-s2.0-85174707802
    2-s2.0-85176146606
    2-s2.0-85178165882
    2-s2.0-85140242438
    2-s2.0-85163947335
    2-s2.0-85160202478
    2-s2.0-85159183627
    2-s2.0-85175480437
    2-s2.0-85150639675
    2-s2.0-85149895087
    2-s2.0-85151850523
    2-s2.0-85164560145
    2-s2.0-85138137895
    2-s2.0-85144727610
    2-s2.0-85132567954
    2-s2.0-85129541562
    2-s2.0-85127263541
    2-s2.0-85134762829
    2-s2.0-85134605028
    2-s2.0-85134207203
    2-s2.0-85130172241
    2-s2.0-85110132246
    2-s2.0-85107774063
    2-s2.0-85100936750
    2-s2.0-85123005832
    2-s2.0-85116901267
Search 'REF(2-s2.0-85093926143)' yielded 5 documents as of 2023-12-18:
    2-s2.0-85174707802
    2-s2.0-85132525373
    2-s2.0-85143791703
    2-s2.0-85130492882
    2-s2.0-85123721902
Search 'REF(2-s2.0-85082441558)' yielded 9 documents as of 2023-12-18:
    2-s2.0-85129353199
    2-s2.0-85153334849
    2-s2.0-85103428030
    2-s2.0-85137993971
    2-s2.0-85119055485
    2-s2.0-85118642294
    2-s2.0-85118769792
    2-s2.0-85113716450
    2-s2.0-85099932402
Search 'REF(2-s2.0-85079239065)' yielded 6 documents as of 2023-12-18:
    2-s2.0-85174707802
    2-s2.0-85132525373
    2-s2.0-85103428030
    2-s2.0-85118769792
    2-s2.0-85101981547
    2-s2.0-85095819851
Search 'REF(2-s2.0-85097380415)' yielded 12 documents as of 2023-12-18:
    2-s2.0-85165089398
    2-s2.0-85149246696
    2-s2.0-85174637694
    2-s2.0-85168569804
    2-s2.0-85143906656
    2-s2.0-85137981454
    2-s2.0-85130756836
    2-s2.0-85129221734
    2-s2.0-85113907936
    2-s2.0-85105052507
    2-s2.0-85136718318
    2-s2.0-85108945554
Search 'REF(2-s2.0-85095734112)' yielded 5 documents as of 2023-12-18:
    2-s2.0-85107683405
    2-s2.0-85143906656
    2-s2.0-85139867862
    2-s2.0-85136934584
    2-s2.0-85130756836
Search 'REF(2-s2.0-85090883258)' yielded 1 document as of 2023-12-18:
    2-s2.0-85115761767
Search 'REF(2-s2.0-85090100247)' yielded 4 documents as of 2023-12-18:
    2-s2.0-85129353199
    2-s2.0-85107683405
    2-s2.0-85113712544
    2-s2.0-85095734112
Search 'REF(2-s2.0-85082444588)' yielded 12 documents as of 2023-12-18:
    2-s2.0-85165002810
    2-s2.0-85130336561
    2-s2.0-85107683405
    2-s2.0-85103428030
    2-s2.0-85137469232
    2-s2.0-85136956557
    2-s2.0-85112863874
    2-s2.0-85119675888
    2-s2.0-85113716450
    2-s2.0-85113712544
    2-s2.0-85108966804
    2-s2.0-85090100247
Search 'REF(2-s2.0-85070525370)' yielded 7 documents as of 2023-12-18:
    2-s2.0-85161865197
    2-s2.0-85147657571
    2-s2.0-85121534481
    2-s2.0-85117894540
    2-s2.0-85106274858
    2-s2.0-85106469791
    2-s2.0-85092658500
Search 'REF(2-s2.0-85070329171)' yielded 5 documents as of 2023-12-18:
    2-s2.0-85174707802
    2-s2.0-85136515209
    2-s2.0-85124421879
    2-s2.0-85143304438
    2-s2.0-85083733398
Search 'REF(2-s2.0-85062645475)' yielded 7 documents as of 2023-12-18:
    2-s2.0-85145965157
    2-s2.0-85103428030
    2-s2.0-85121778825
    2-s2.0-85118769792
    2-s2.0-85113716450
    2-s2.0-85082441558
    2-s2.0-85082444588
Search 'REF(2-s2.0-85051863772)' yielded 1 document as of 2023-12-18:
    2-s2.0-85079239065
Search 'REF(2-s2.0-85035209468)' yielded 14 documents as of 2023-12-18:
    2-s2.0-85145352614
    2-s2.0-85142355054
    2-s2.0-85122034807
    2-s2.0-85111122280
    2-s2.0-85095974840
    2-s2.0-85092507655
    2-s2.0-85089073530
    2-s2.0-85087001715
    2-s2.0-85081991187
    2-s2.0-85053778744
    2-s2.0-85067426015
    2-s2.0-85048884985
    2-s2.0-85035242264
    2-s2.0-85035210635

In [4]:
df = pd.DataFrame(acc, columns=["Paper title", "Paper eid", "Paper doi", "Citing paper title", "Citing paper eid", "Citing paper doi"])
df.to_csv("data/scopus-citations-{}.csv".format(time.time()), index=False)
df

,Paper title,Paper eid,Paper doi,Citing paper title,Citing paper eid,Citing paper doi
0,HAMLET: A framework for Human-centered AutoML ...,2-s2.0-85145965157,10.1016/j.future.2022.12.035,,,
1,Trajectory-Based Spatiotemporal Entity Linking,2-s2.0-85096846619,10.1109/TKDE.2020.3036633,Colossal Trajectory Mining: A unifying approac...,2-s2.0-85174707802,10.1016/j.eswa.2023.122055
2,Trajectory-Based Spatiotemporal Entity Linking,2-s2.0-85096846619,10.1109/TKDE.2020.3036633,Leveraging user itinerary to improve personali...,2-s2.0-85149039992,10.1007/s00778-023-00787-z
3,Trajectory-Based Spatiotemporal Entity Linking,2-s2.0-85096846619,10.1109/TKDE.2020.3036633,A Survey and Experimental Study on Privacy-Pre...,2-s2.0-85132525373,10.1109/TKDE.2022.3174204
4,Trajectory-Based Spatiotemporal Entity Linking,2-s2.0-85096846619,10.1109/TKDE.2020.3036633,Information Resilience: the nexus of responsib...,2-s2.0-85123164859,10.1007/s00778-021-00720-2
...,...,...,...,...,...,...
182,Towards a foundational API for resilient distr...,2-s2.0-85035209468,10.1109/FAS-W.2017.116,Modelling and simulation of Opportunistic IoT ...,2-s2.0-85053778744,10.1016/j.future.2018.09.005
183,Towards a foundational API for resilient distr...,2-s2.0-85035209468,10.1109/FAS-W.2017.116,The share operator for field-based coordination,2-s2.0-85067426015,10.1007/978-3-030-22397-7_4
184,Towards a foundational API for resilient distr...,2-s2.0-85035209468,10.1109/FAS-W.2017.116,From field-based coordination to aggregate com...,2-s2.0-85048884985,10.1007/978-3-319-92408-3_12
185,Towards a foundational API for resilient distr...,2-s2.0-85035209468,10.1109/FAS-W.2017.116,Practical Aggregate Programming with Protelis,2-s2.0-85035242264,10.1109/FAS-W.2017.186
186,Towards a foundational API for resilient distr...,2-s2.0-85035209468,10.1109/FAS-W.2017.116,Self-Stabilising Target Counting in Wireless S...,2-s2.0-85035210635,10.1109/SASO.2017.10

In [5]:
import numpy as np
df = df.replace("", np.nan)
df["Citing paper title"].isna()

0       True
1      False
2      False
3      False
4      False
       ...
182    False
183    False
184    False
185    False
186    False
Name: Citing paper title, Length: 187, dtype: bool

Total citations

In [6]:
s = df.groupby(["Paper title"])["Citing paper title"].count()
s.sum()

182

Citation details

In [7]:
s.sort_values(ascending=False).to_csv("data/scopus-summary-{}.csv".format(time.time()))